### PR TITLE
[WIP] Better fix for member selects inside module-info.java

### LINKED ISSUE #533: Crash with module-info import
When upgrading from 0.9.2 to 0.9.3 with JDK11, the following error occurs:

```
/Users/ben/projects/caffeine/caffeine/src/main/java/module-info.java:5: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  requires static com.google.errorprone.annotations;
                                       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.10.0
     BugPattern: NullAway
     Stack Trace:
     java.lang.RuntimeException: expression is not inside a method, lambda or initializer block!
        at com.uber.nullaway.dataflow.DataFlow.resultFor(DataFlow.java:261)
        at com.uber.nullaway.dataflow.DataFlow.resultForExpr(DataFlow.java:253)
        at com.uber.nullaway.dataflow.DataFlow.expressionDataflow(DataFlow.java:196)
        at com.uber.nullaway.dataflow.AccessPathNullnessAnalysis.getNullness(AccessPathNullnessAnalysis.java:127)
        at com.uber.nullaway.NullAway.nullnessFromDataflow(NullAway.java:1979)
        at com.uber.nullaway.NullAway.mayBeNullFieldAccess(NullAway.java:1999)
        at com.uber.nullaway.NullAway.mayBeNullExpr(NullAway.java:1932)
        at com.uber.nullaway.NullAway.matchDereference(NullAway.java:2016)
        at com.uber.nullaway.NullAway.matchMemberSelect(NullAway.java:439)
        at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:726)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:150)
        ...
```

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #533

### CODE REVIEW

**Comment by msridhar** [comment]
I ran a jmh test with current master and with a branch including this PR and also #543.  Master results:

```
Benchmark                      Mode  Cnt   Score   Error  Units
AutodisposeBenchmark.compile  thrpt   25  17.290 ± 0.193  ops/s
CaffeineBenchmark.compile     thrpt   25   4.176 ± 0.042  ops/s
```

With the PRs applied:
```
Benchmark                      Mode  Cnt   Score   Error  Units
AutodisposeBenchmark.compile  thrpt   25  17.310 ± 0.173  ops/s
CaffeineBenchmark.compile     thrpt   25   4.118 ± 0.036  ops/s
```

Differences are in the noise, but barely so for Caffeine.  Also, in [this previous test](https://github.com/uber/NullAway/pull/520#issuecomment-998226108) from a few weeks ago things seemed to be running every so slightly faster.  Of course, something could have changed on my machine between then and now.  I'll try to do some more tests of recent versions to see if I can consistently find some issue.

For now, I don't think any potential perf regression is at a worrysome level.  Will poke a bit more.

**Comment by msridhar** [comment]
After trying some more measurements, I think our jmh setup is a bit too noisy to detect possible 1-2% perf regressions.  It's possible running the jmh harness outside of Gradle (i.e., killing the Gradle daemon and invoking the JVM directly) might stabilize things a bit more, but I'm not sure.  I am comfortable that these changes do not seem to be introducing a large perf regression.  But @lazaroclapp if you want me to try to do more careful testing, let me know.

**Comment by msridhar** [comment]
Another perf update: I managed to run jmh on a different machine in a config where the noise was reduced a bit.  (Running jmh directly rather than via Gradle does seem to help a bit.)  Bottom line, it looks like any perf differences are in the noise.  It's still hard to be 100% confident of this without doing a ton of runs.  I do worry about very slight perf regressions adding up over time...but we're still doing a lot better than we used to with this stuff.  Probably would be good to dig into profiles once in a while to see if anything new pops out.

**Comment by lazaroclapp** [comment]
Not related to this PR, but I wonder if there is a good automatic way that we can check for long term performance regressions. Maybe just run our perf testing on a dedicated machine for the last ~5 NullAway releases before cutting a new release? Will probably not happen for 0.9.5, though.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java [hunk 1]
```diff
@@ -1931,12 +1960,18 @@ private boolean mayBeNullExpr(VisitorState state, ExpressionTree expr) {
         exprMayBeNull = false;
         break;
       case MEMBER_SELECT:
-        // A MemberSelectTree for a field dereference or method call cannot have a null symbol; see
-        // comments in matchMemberSelect()
-        exprMayBeNull = exprSymbol == null ? false : mayBeNullFieldAccess(state, expr, exprSymbol);
+        if (exprSymbol == null) {
```
Comment (lazaroclapp) [inline nullaway/src/main/java/com/uber/nullaway/NullAway.java:1963]: So, the change here is that the tree `t1` corresponding to module symbol `s1` can have a `t2=t1.getExpression()` such that `s2=ASTHelpers.getSymbol(t2)` is `null`. Correct? And that's the only case we are aware of or the only case up to JDK 17 (involving `MEMBER_SELECT` or `IDENTIFIER`, I mean, as opposed to some parenthesized expression)? 

So, with the added check in line 457, no such `t2` can flow into `matchDereference(...)`, which means no such `s2` ends up here. Right?

File: jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwayModuleInfoTests.java [hunk 2]
```diff
@@ -36,6 +36,7 @@ public void testModuleInfo() {
         .addSourceLines(
             "module-info.java",
             "module com.uber.mymodule {",
+            "  requires java.base;",
```
Comment (lazaroclapp) [inline jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwayModuleInfoTests.java:39]: The difference here isn't `static` vs not, but just that this one is a chain of two derefs so the "base expression" is just `java` which is an identifier rather than a member select expression. Correct?

**Review by lazaroclapp — APPROVED** [review]
Brief questions to make sure I understand the change, but overall looks good to me.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 1 above)
Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:1963]: Yes, that's exactly right.  The idea is if `matchDereference()` is called at line 461, and `tree.getExpression()` at that line is an identifier or member-select tree `t`, then `ASTHelpers.getSymbol(t)` cannot be null.  The check at line 457 stops the call at line 461 for member-select trees representing refs to modules, which is the case coming up in #533.  If NullAway crashes again in the future due to this type of issue, the error message should be more understandable.

Should I add any more docs / comments around this @lazaroclapp?

File: jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwayModuleInfoTests.java (hunk 2 above)
Comment (msridhar) [reply jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwayModuleInfoTests.java:39]: Yes.  For the previous case `require static org.checkerframework.checker.qual;`, `matchMemberSelect()` would get called with the sub-expression `org.checkerframework`, but since the symbol for that sub-expression was null, `matchDeference()` was not called for identifier `org`.  `java.base` has a non-null `Symbol` representing the module, so `matchDereference()` was being called with identifier `java`, leading to the new crash.

**Comment by msridhar** [comment]
> Not related to this PR, but I wonder if there is a good automatic way that we can check for long term performance regressions. Maybe just run our perf testing on a dedicated machine for the last ~5 NullAway releases before cutting a new release? Will probably not happen for 0.9.5, though.

Yes, this is a really good idea.  Testing a bunch of releases will let us catch a bunch of small regressions that are adding up to something significant (though even if we discover that is happening, I guess it's unclear what exactly to do about it....)  We don't consistently do perf testing for every PR, so this could catch larger unexpected regressions as well.

File: nullaway/src/main/java/com/uber/nullaway/NullAway.java (hunk 1 above)
Comment (lazaroclapp) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:1963]: I don't think so. A lot of the questions arise from me trying to understand what changed with this fix, but not what we are trying to assert here. I think the comments are fine for the code in its steady state.

Comment (msridhar) [reply nullaway/src/main/java/com/uber/nullaway/NullAway.java:1963]: Ok, thanks!  I will go ahead and merge then

File: jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwayModuleInfoTests.java (hunk 2 above)
Comment (lazaroclapp) [reply jdk17-unit-tests/src/test/java/com/uber/nullaway/jdk17/NullAwayModuleInfoTests.java:39]: Maybe here it's worth having a small comment:
```
// Important: two-level deep module tests matching of identifier `java` (see #544)
```
Not sure how I feel about a PR's code referring to itself, but a full explanation might be too verbose.
